env:
  browser: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript

rules:
  "@typescript-eslint/no-unused-vars": ["error"]
  "no-console": ["error"]

ignorePatterns:
  - dist
  - coverage
